"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */var w=require("vue");function _(e,t){const{localeRef:a,i18nPlugin:o,cachePlugin:s,colorPlugin:d,sizePlugin:c,templatePlugin:n}=t;e.provide("locale",a),e.provide("app-locale",a),s&&e.use(s),e.use(n),e.use(d),e.use(c),o.setupVueApp&&o.setupVueApp(e),e.config.globalProperties.$getLocale=()=>a.value,e.config.globalProperties.$setLocale=l=>{o.api?.changeLocale&&o.api.changeLocale(l)},(void 0).DEV&&typeof window<"u"&&(window.__APP__=e)}const f=new WeakMap;function m(e,t,a,o,s,d){const c=[];if(e?.state){e.state.set("locale",t.value);const n=w.watch(t,l=>{e.state.set("locale",l)},{flush:"post"});c.push(n)}try{const n=e?.api,l=e?.router,i=n?.i18n;if(i&&l&&typeof i.on=="function"){let u=null;const g=E=>{u!==null&&clearTimeout(u),u=window.setTimeout(()=>{try{const p=(typeof l.getCurrentRoute=="function"?l.getCurrentRoute().value:null)?.meta?.titleKey,r=typeof n?.t=="function"?n.t.bind(n):h=>h;p?document.title=`${r(p)} - ${r("app.name")}`:document.title=r("app.name")}catch(p){console.warn("Failed to update title on locale change:",p)}u=null},100)};i.on("localeChanged",g),c.push(()=>{u!==null&&(clearTimeout(u),u=null),typeof i.off=="function"&&i.off("localeChanged",g)})}}catch(n){console.warn("i18n title sync setup failed:",n)}if(e&&c.length>0&&(f.set(e,c),typeof e.onBeforeUnmount=="function"&&e.onBeforeUnmount(()=>{y(e)})),(void 0).DEV)try{typeof window<"u"&&(window.__ENGINE__=e(window).__LOCALE__=t)}catch{}}function y(e){const t=f.get(e);t&&(t.forEach(a=>{try{a()}catch(o){console.warn("Error during engine cleanup:",o)}}),f.delete(e))}exports.cleanupEngineReady=y,exports.setupEngineReady=m,exports.setupVueApp=_;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=app-setup.cjs.map
