/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as w,ref as r,createElementBlock as c,openBlock as m,createElementVNode as u,createCommentVNode as B,toDisplayString as l}from"vue";import{useAppCache as y}from"../composables/useAppCache.js";const f={class:"cache-demo"},g={class:"demo-section"},k={key:0,class:"demo-result"},M={class:"demo-section"},S={key:0,class:"demo-result"},A={class:"demo-section"},N={key:0,class:"demo-result"};var R=w({__name:"CacheDemo",setup(x){const a=y(),o=r(null),n=r(""),s=r(null),F=async()=>{await a.set("demo-data",{message:"Hello Cache!",timestamp:Date.now()}),console.log("\u7F13\u5B58\u5DF2\u8BBE\u7F6E")},v=async()=>{o.value=await a.get("demo-data"),console.log("\u7F13\u5B58\u5DF2\u83B7\u53D6:",o.value)},D=async()=>{await a.remove("demo-data"),o.value=null,console.log("\u7F13\u5B58\u5DF2\u5220\u9664")},h=async()=>{const e=Date.now(),t=await a.remember("expensive-data",async()=>(await new Promise(b=>setTimeout(b,1e3)),{computed:Math.random()})),d=Date.now()-e;n.value=`\u7B2C\u4E00\u6B21\u8017\u65F6: ${d}ms, \u6570\u636E: ${JSON.stringify(t)}`;const i=Date.now();await a.remember("expensive-data",async()=>({computed:999}));const E=Date.now()-i;n.value+=` | \u7B2C\u4E8C\u6B21\u8017\u65F6: ${E}ms (\u4ECE\u7F13\u5B58)`},C=async()=>{const e=await a.getStats();e&&(s.value={totalItems:e.totalItems,totalSize:e.totalSize,hitRate:e.hits&&e.misses?Math.round(e.hits/(e.hits+e.misses)*100):0})},p=e=>{if(e===0)return"0 B";const t=1024,d=["B","KB","MB","GB"],i=Math.floor(Math.log(e)/Math.log(t));return Math.round(e/Math.pow(t,i)*100)/100+" "+d[i]};return(e,t)=>(m(),c("div",f,[t[3]||(t[3]=u("h3",null,"\u7F13\u5B58\u529F\u80FD\u6F14\u793A",-1)),u("div",g,[t[0]||(t[0]=u("h4",null,"1. \u57FA\u7840\u7F13\u5B58\u64CD\u4F5C",-1)),u("div",{class:"demo-actions"},[u("button",{onClick:F,class:"demo-btn"},"\u8BBE\u7F6E\u7F13\u5B58"),u("button",{onClick:v,class:"demo-btn"},"\u83B7\u53D6\u7F13\u5B58"),u("button",{onClick:D,class:"demo-btn"},"\u5220\u9664\u7F13\u5B58")]),o.value?(m(),c("div",k," \u7F13\u5B58\u503C: "+l(JSON.stringify(o.value)),1)):B("v-if",!0)]),u("div",M,[t[1]||(t[1]=u("h4",null,"2. Remember \u6A21\u5F0F\uFF08\u8BB0\u5FC6\u5316\uFF09",-1)),u("button",{onClick:h,class:"demo-btn"},"\u6D4B\u8BD5 Remember"),n.value?(m(),c("div",S," \u7ED3\u679C: "+l(n.value),1)):B("v-if",!0)]),u("div",A,[t[2]||(t[2]=u("h4",null,"3. \u7F13\u5B58\u7EDF\u8BA1",-1)),u("button",{onClick:C,class:"demo-btn"},"\u67E5\u770B\u7EDF\u8BA1"),s.value?(m(),c("div",N,[u("div",null,"\u603B\u9879\u6570: "+l(s.value.totalItems),1),u("div",null,"\u603B\u5927\u5C0F: "+l(p(s.value.totalSize)),1),u("div",null,"\u547D\u4E2D\u7387: "+l(s.value.hitRate)+"%",1)])):B("v-if",!0)])]))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{R as default};
//# sourceMappingURL=CacheDemo.vue2.js.map
