/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as E,ref as _,computed as o,createElementBlock as s,onMounted as x,onUnmounted as B,openBlock as n,createElementVNode as t,createVNode as f,unref as c,toDisplayString as r,normalizeClass as g,Transition as N,withCtx as S,createCommentVNode as p,withModifiers as V,Fragment as z,renderList as D,createBlock as F}from"vue";import{useI18n as M}from"../i18n/index.js";import{availableLocales as u}from"../locales/index.js";import{ChevronDown as T,Check as G}from"lucide-vue-next";const H={class:"language-switcher"},I=["title"],J={class:"flag"},O={class:"name"},U=["onClick"],j={class:"flag"},q={class:"name"};var A=E({__name:"LanguageSwitcher",setup(K){const{locale:k,setLocale:w,t:C}=M(),e=_(!1),i=o(()=>k.value),d=o(()=>u.find(a=>a.code===i.value)||u[0]),h=o(()=>d.value.name),L=o(()=>d.value.flag),y=()=>{e.value=!e.value},b=async a=>{await w(a),e.value=!1},m=a=>{a.target.closest(".language-switcher")||(e.value=!1)};return x(()=>{document.addEventListener("click",m)}),B(()=>{document.removeEventListener("click",m)}),(a,v)=>(n(),s("div",H,[t("button",{onClick:y,class:"language-button",title:c(C)("nav.language")},[t("span",J,r(L.value),1),t("span",O,r(h.value),1),f(c(T),{class:g(["arrow",{open:e.value}])},null,8,["class"])],8,I),f(N,{name:"dropdown"},{default:S(()=>[e.value?(n(),s("div",{key:0,class:"language-dropdown",onClick:v[0]||(v[0]=V(()=>{},["stop"]))},[(n(!0),s(z,null,D(c(u),l=>(n(),s("button",{key:l.code,onClick:P=>b(l.code),class:g(["language-option",{active:i.value===l.code}])},[t("span",j,r(l.flag),1),t("span",q,r(l.name),1),i.value===l.code?(n(),F(c(G),{key:0,class:"check"})):p("v-if",!0)],10,U))),128))])):p("v-if",!0)]),_:1})]))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{A as default};
//# sourceMappingURL=LanguageSwitcher.vue2.js.map
