/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as v,reactive as b,ref as y,createElementBlock as s,openBlock as i,createElementVNode as e,createCommentVNode as n,toDisplayString as d,withModifiers as c,withDirectives as p,vModelText as f,vModelCheckbox as w,createTextVNode as h}from"vue";const C={class:"login-container"},k={class:"login-card"},q={class:"login-header"},x={class:"login-title"},D={key:0,class:"login-subtitle"},E={class:"form-group"},V={class:"form-group"},R={class:"form-options"},S={class:"checkbox-label"},L=["disabled"],P={key:0,class:"register-link"};var A=v({__name:"LoginTemplate",props:{title:{type:String,required:!1,default:"\u6B22\u8FCE\u767B\u5F55"},subtitle:{type:String,required:!1,default:""},logo:{type:String,required:!1,default:""},showRemember:{type:Boolean,required:!1,default:!0},showRegister:{type:Boolean,required:!1,default:!0},showForgotPassword:{type:Boolean,required:!1,default:!0},onLogin:{type:Function,required:!1},onRegister:{type:Function,required:!1},onForgotPassword:{type:Function,required:!1}},setup(m){const o=m,t=b({username:"",password:"",remember:!1}),a=y(!1);async function g(){if(o.onLogin){a.value=!0;try{await o.onLogin(t)}catch(r){console.error("Login failed:",r)}finally{a.value=!1}}}function F(){o.onRegister?.()}function B(){o.onForgotPassword?.()}return(r,u)=>(i(),s("div",C,[e("div",k,[e("div",q,[e("h1",x,d(r.title||"\u6B22\u8FCE\u767B\u5F55"),1),r.subtitle?(i(),s("p",D,d(r.subtitle),1)):n("v-if",!0)]),e("form",{onSubmit:c(g,["prevent"]),class:"login-form"},[e("div",E,[u[3]||(u[3]=e("label",{for:"username"},"\u7528\u6237\u540D / \u90AE\u7BB1",-1)),p(e("input",{id:"username","onUpdate:modelValue":u[0]||(u[0]=l=>t.username=l),type:"text",placeholder:"\u8BF7\u8F93\u5165\u7528\u6237\u540D\u6216\u90AE\u7BB1",required:""},null,512),[[f,t.username]])]),e("div",V,[u[4]||(u[4]=e("label",{for:"password"},"\u5BC6\u7801",-1)),p(e("input",{id:"password","onUpdate:modelValue":u[1]||(u[1]=l=>t.password=l),type:"password",placeholder:"\u8BF7\u8F93\u5165\u5BC6\u7801",required:""},null,512),[[f,t.password]])]),e("div",R,[e("label",S,[p(e("input",{"onUpdate:modelValue":u[2]||(u[2]=l=>t.remember=l),type:"checkbox"},null,512),[[w,t.remember]]),u[5]||(u[5]=e("span",null,"\u8BB0\u4F4F\u6211",-1))]),r.onForgotPassword?(i(),s("a",{key:0,href:"#",class:"forgot-link",onClick:c(B,["prevent"])}," \u5FD8\u8BB0\u5BC6\u7801\uFF1F ")):n("v-if",!0)]),e("button",{type:"submit",class:"login-button",disabled:a.value},d(a.value?"\u767B\u5F55\u4E2D...":"\u767B\u5F55"),9,L),r.onRegister?(i(),s("div",P,[u[6]||(u[6]=h(" \u8FD8\u6CA1\u6709\u8D26\u53F7\uFF1F ",-1)),e("a",{href:"#",onClick:c(F,["prevent"])},"\u7ACB\u5373\u6CE8\u518C")])):n("v-if",!0)],32)])]))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{A as default};
//# sourceMappingURL=LoginTemplate.vue2.js.map
