/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as V,ref as f,computed as b,createElementBlock as a,openBlock as t,createElementVNode as d,createCommentVNode as l,normalizeClass as k,createVNode as u,withKeys as S,toDisplayString as I}from"vue";import"./LucideIcon.vue.js";import i from"./LucideIcon.vue2.js";const w={class:"base-input-wrapper"},z={key:0,class:"input-prefix"},B=["type","value","placeholder","disabled","maxlength","autocomplete"],C={key:2,class:"input-suffix"},M={key:0,class:"input-error"};var N=V({__name:"BaseInput",props:{modelValue:{type:String,required:!0},type:{type:String,required:!1,default:"text"},placeholder:{type:String,required:!1,default:""},disabled:{type:Boolean,required:!1,default:!1},maxlength:{type:Number,required:!1},autocomplete:{type:String,required:!1,default:"off"},prefixIcon:{type:String,required:!1},suffixIcon:{type:String,required:!1},clearable:{type:Boolean,required:!1,default:!1},errorMessage:{type:String,required:!1}},emits:["update:modelValue","enter","clear"],setup(c,{emit:m}){const p=c,n=m,o=f(!1),r=f(!1),y=b(()=>p.type==="password"&&r.value?"text":p.type),v=e=>{const s=e.target;n("update:modelValue",s.value)},g=()=>{o.value=!0},x=()=>{o.value=!1},h=()=>{n("update:modelValue",""),n("clear")},q=()=>{r.value=!r.value};return(e,s)=>(t(),a("div",w,[d("div",{class:k(["input-container",{"has-error":e.errorMessage,"is-focused":o.value}])},[e.prefixIcon?(t(),a("span",z,[u(i,{name:e.prefixIcon,size:18},null,8,["name"])])):l("v-if",!0),d("input",{type:y.value,value:e.modelValue,placeholder:e.placeholder,disabled:e.disabled,maxlength:e.maxlength,autocomplete:e.autocomplete,onInput:v,onFocus:g,onBlur:x,onKeyup:s[0]||(s[0]=S(E=>e.$emit("enter"),["enter"])),class:"input-field"},null,40,B),e.type==="password"?(t(),a("span",{key:1,class:"input-suffix",onClick:q},[u(i,{name:r.value?"eyeOff":"eye",size:18},null,8,["name"])])):l("v-if",!0),e.suffixIcon&&e.type!=="password"?(t(),a("span",C,[u(i,{name:e.suffixIcon,size:18},null,8,["name"])])):l("v-if",!0),e.clearable&&e.modelValue?(t(),a("span",{key:3,class:"input-suffix",onClick:h},[u(i,{name:"x",size:16})])):l("v-if",!0)],2),e.errorMessage?(t(),a("div",M,I(e.errorMessage),1)):l("v-if",!0)]))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{N as default};
//# sourceMappingURL=BaseInput.vue2.js.map
