/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as h,ref as m,createElementBlock as t,onMounted as v,onBeforeUnmount as y,openBlock as u,createVNode as B,createElementVNode as s,createCommentVNode as C,normalizeClass as V}from"vue";import"./BaseInput.vue.js";import k from"./BaseInput.vue2.js";const q={class:"image-captcha-wrapper"},x=["src"],U={key:1,class:"captcha-placeholder"},N={key:2,class:"captcha-loading"};var S=h({__name:"ImageCaptcha",props:{modelValue:{type:String,required:!0},imageUrl:{type:String,required:!1},placeholder:{type:String,required:!1,default:"\u8BF7\u8F93\u5165\u9A8C\u8BC1\u7801"},maxlength:{type:Number,required:!1,default:4},errorMessage:{type:String,required:!1},autoLoad:{type:Boolean,required:!1,default:!0}},emits:["update:modelValue","refresh","enter"],setup(p,{emit:g}){const o=p,i=g,n=m(o.modelValue),r=m(!1);let a=null;const f=e=>{n.value=e,i("update:modelValue",e)},d=async()=>{r.value||(r.value=!0,i("refresh"),a!==null&&clearTimeout(a),a=window.setTimeout(()=>{r.value=!1,a=null},500))};return v(()=>{o.autoLoad&&!o.imageUrl&&d()}),y(()=>{a!==null&&(clearTimeout(a),a=null)}),(e,l)=>(u(),t("div",q,[B(k,{modelValue:n.value,"onUpdate:modelValue":[l[0]||(l[0]=c=>n.value=c),f],placeholder:e.placeholder,maxlength:e.maxlength,"error-message":e.errorMessage,"prefix-icon":"icon-shield",onEnter:l[1]||(l[1]=c=>e.$emit("enter"))},null,8,["modelValue","placeholder","maxlength","error-message"]),s("div",{class:"captcha-image-container",onClick:d},[e.imageUrl?(u(),t("img",{key:0,src:e.imageUrl,alt:"\u9A8C\u8BC1\u7801",class:V(["captcha-image",{loading:r.value}]),loading:"lazy",decoding:"async"},null,10,x)):(u(),t("div",U,[...l[2]||(l[2]=[s("span",null,"\u70B9\u51FB\u83B7\u53D6\u9A8C\u8BC1\u7801",-1)])])),r.value?(u(),t("div",N,[...l[3]||(l[3]=[s("span",{class:"loading-spinner"},null,-1)])])):C("v-if",!0)])]))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{S as default};
//# sourceMappingURL=ImageCaptcha.vue2.js.map
