/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as k,reactive as h,computed as f,createElementBlock as a,openBlock as m,withModifiers as i,createVNode as p,createElementVNode as l,normalizeClass as A}from"vue";import"./BaseInput.vue.js";import"./SmsCaptcha.vue.js";import"./RememberCheckbox.vue.js";import{validatePhone as C,validateSmsCode as E}from"../utils/validators.js";import $ from"./BaseInput.vue2.js";import y from"./SmsCaptcha.vue2.js";import w from"./RememberCheckbox.vue2.js";const x={class:"form-options"},N={class:"option-links"},S=["disabled"],U={key:0,class:"button-loading"},D={key:1};var P=k({__name:"PhoneLoginForm",props:{loading:{type:Boolean,required:!1,default:!1}},emits:["submit","send-sms","switch-to-username","register"],setup(B,{emit:F}){const v=B,d=F,o=h({phone:"",smsCode:"",remember:!1}),n=h({phone:"",smsCode:""}),r=f(()=>v.loading),g=f(()=>o.phone&&o.smsCode),c=s=>{n[s]=""},b=()=>{let s=!0;return o.phone?C(o.phone)||(n.phone="\u8BF7\u8F93\u5165\u6B63\u786E\u7684\u624B\u673A\u53F7",s=!1):(n.phone="\u8BF7\u8F93\u5165\u624B\u673A\u53F7",s=!1),o.smsCode?E(o.smsCode)||(n.smsCode="\u8BF7\u8F93\u51656\u4F4D\u6570\u5B57\u9A8C\u8BC1\u7801",s=!1):(n.smsCode="\u8BF7\u8F93\u5165\u9A8C\u8BC1\u7801",s=!1),s},t=()=>{r.value||b()&&d("submit",{...o})},V=s=>{if(!C(s)){n.phone="\u8BF7\u8F93\u5165\u6B63\u786E\u7684\u624B\u673A\u53F7";return}d("send-sms",s)};return(s,e)=>(m(),a("form",{class:"phone-login-form",onSubmit:i(t,["prevent"])},[p($,{modelValue:o.phone,"onUpdate:modelValue":[e[0]||(e[0]=u=>o.phone=u),e[1]||(e[1]=u=>c("phone"))],placeholder:"\u8BF7\u8F93\u5165\u624B\u673A\u53F7","prefix-icon":"icon-phone",maxlength:11,"error-message":n.phone,clearable:!0,onEnter:t},null,8,["modelValue","error-message"]),p(y,{modelValue:o.smsCode,"onUpdate:modelValue":[e[2]||(e[2]=u=>o.smsCode=u),e[3]||(e[3]=u=>c("smsCode"))],phone:o.phone,"error-message":n.smsCode,onSend:V,onEnter:t},null,8,["modelValue","phone","error-message"]),l("div",x,[p(w,{modelValue:o.remember,"onUpdate:modelValue":e[4]||(e[4]=u=>o.remember=u)},null,8,["modelValue"]),l("div",N,[l("a",{href:"#",class:"option-link",onClick:e[5]||(e[5]=i(u=>s.$emit("switch-to-username"),["prevent"]))}," \u7528\u6237\u540D\u767B\u5F55 "),e[7]||(e[7]=l("span",{class:"divider"},"|",-1)),l("a",{href:"#",class:"option-link",onClick:e[6]||(e[6]=i(u=>s.$emit("register"),["prevent"]))}," \u7ACB\u5373\u6CE8\u518C ")])]),l("button",{type:"submit",class:A(["login-button",{loading:r.value}]),disabled:r.value||!g.value},[r.value?(m(),a("span",U)):(m(),a("span",D,"\u767B\u5F55"))],10,S)],32))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{P as default};
//# sourceMappingURL=PhoneLoginForm.vue2.js.map
