/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as V,reactive as i,computed as f,createElementBlock as p,openBlock as n,withModifiers as h,createVNode as t,createElementVNode as c,normalizeClass as E}from"vue";import"./BaseInput.vue.js";import"./ImageCaptcha.vue.js";import"./RememberCheckbox.vue.js";import{validateUsername as U,validatePassword as D,validateCaptcha as k}from"../utils/validators.js";import F from"./BaseInput.vue2.js";import y from"./ImageCaptcha.vue2.js";import $ from"./RememberCheckbox.vue2.js";const x={class:"form-options"},N=["disabled"],q={key:0,class:"button-loading"},A={key:1};var S=V({__name:"UsernameLoginForm",props:{captchaUrl:{type:String,required:!1},loading:{type:Boolean,required:!1,default:!1}},emits:["submit","refresh-captcha","forgot-password"],setup(B,{emit:g}){const w=B,d=g,e=i({username:"",password:"",captcha:"",remember:!1}),s=i({username:"",password:"",captcha:""}),o=f(()=>w.loading),C=f(()=>e.username&&e.password&&e.captcha),m=r=>{s[r]=""},b=()=>{let r=!0;return e.username?U(e.username)||(s.username="\u7528\u6237\u540D\u683C\u5F0F\u4E0D\u6B63\u786E",r=!1):(s.username="\u8BF7\u8F93\u5165\u7528\u6237\u540D",r=!1),e.password?D(e.password)||(s.password="\u5BC6\u7801\u683C\u5F0F\u4E0D\u6B63\u786E",r=!1):(s.password="\u8BF7\u8F93\u5165\u5BC6\u7801",r=!1),e.captcha?k(e.captcha)||(s.captcha="\u9A8C\u8BC1\u7801\u683C\u5F0F\u4E0D\u6B63\u786E",r=!1):(s.captcha="\u8BF7\u8F93\u5165\u9A8C\u8BC1\u7801",r=!1),r},l=()=>{o.value||b()&&d("submit",{...e})},v=()=>{e.captcha="",d("refresh-captcha")};return(r,a)=>(n(),p("form",{class:"username-login-form",onSubmit:h(l,["prevent"])},[t(F,{modelValue:e.username,"onUpdate:modelValue":[a[0]||(a[0]=u=>e.username=u),a[1]||(a[1]=u=>m("username"))],placeholder:"\u8BF7\u8F93\u5165\u7528\u6237\u540D","prefix-icon":"icon-user","error-message":s.username,clearable:!0,onEnter:l},null,8,["modelValue","error-message"]),t(F,{modelValue:e.password,"onUpdate:modelValue":[a[2]||(a[2]=u=>e.password=u),a[3]||(a[3]=u=>m("password"))],type:"password",placeholder:"\u8BF7\u8F93\u5165\u5BC6\u7801","prefix-icon":"icon-lock","error-message":s.password,onEnter:l},null,8,["modelValue","error-message"]),t(y,{modelValue:e.captcha,"onUpdate:modelValue":[a[4]||(a[4]=u=>e.captcha=u),a[5]||(a[5]=u=>m("captcha"))],"image-url":r.captchaUrl,"error-message":s.captcha,onRefresh:v,onEnter:l},null,8,["modelValue","image-url","error-message"]),c("div",x,[t($,{modelValue:e.remember,"onUpdate:modelValue":a[6]||(a[6]=u=>e.remember=u)},null,8,["modelValue"]),c("a",{href:"#",class:"forgot-password",onClick:a[7]||(a[7]=h(u=>r.$emit("forgot-password"),["prevent"]))}," \u5FD8\u8BB0\u5BC6\u7801\uFF1F ")]),c("button",{type:"submit",class:E(["login-button",{loading:o.value}]),disabled:o.value||!C.value},[o.value?(n(),p("span",q)):(n(),p("span",A,"\u767B\u5F55"))],10,N)],32))}});/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{S as default};
//# sourceMappingURL=UsernameLoginForm.vue2.js.map
