"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */Object.defineProperty(exports,"__esModule",{value:!0});var e=require("vue");require("./LucideIcon.vue.cjs");var r=require("./LucideIcon.vue2.cjs");const v={class:"base-input-wrapper"},g={key:0,class:"input-prefix"},k=["type","value","placeholder","disabled","maxlength","autocomplete"],V={key:2,class:"input-suffix"},x={key:0,class:"input-error"};var B=e.defineComponent({__name:"BaseInput",props:{modelValue:{type:String,required:!0},type:{type:String,required:!1,default:"text"},placeholder:{type:String,required:!1,default:""},disabled:{type:Boolean,required:!1,default:!1},maxlength:{type:Number,required:!1},autocomplete:{type:String,required:!1,default:"off"},prefixIcon:{type:String,required:!1},suffixIcon:{type:String,required:!1},clearable:{type:Boolean,required:!1,default:!1},errorMessage:{type:String,required:!1}},emits:["update:modelValue","enter","clear"],setup(s,{emit:i}){const n=s,u=i,o=e.ref(!1),a=e.ref(!1),p=e.computed(()=>n.type==="password"&&a.value?"text":n.type),c=t=>{const l=t.target;u("update:modelValue",l.value)},d=()=>{o.value=!0},f=()=>{o.value=!1},m=()=>{u("update:modelValue",""),u("clear")},y=()=>{a.value=!a.value};return(t,l)=>(e.openBlock(),e.createElementBlock("div",v,[e.createElementVNode("div",{class:e.normalizeClass(["input-container",{"has-error":t.errorMessage,"is-focused":o.value}])},[t.prefixIcon?(e.openBlock(),e.createElementBlock("span",g,[e.createVNode(r.default,{name:t.prefixIcon,size:18},null,8,["name"])])):e.createCommentVNode("v-if",!0),e.createElementVNode("input",{type:p.value,value:t.modelValue,placeholder:t.placeholder,disabled:t.disabled,maxlength:t.maxlength,autocomplete:t.autocomplete,onInput:c,onFocus:d,onBlur:f,onKeyup:l[0]||(l[0]=e.withKeys(q=>t.$emit("enter"),["enter"])),class:"input-field"},null,40,k),t.type==="password"?(e.openBlock(),e.createElementBlock("span",{key:1,class:"input-suffix",onClick:y},[e.createVNode(r.default,{name:a.value?"eyeOff":"eye",size:18},null,8,["name"])])):e.createCommentVNode("v-if",!0),t.suffixIcon&&t.type!=="password"?(e.openBlock(),e.createElementBlock("span",V,[e.createVNode(r.default,{name:t.suffixIcon,size:18},null,8,["name"])])):e.createCommentVNode("v-if",!0),t.clearable&&t.modelValue?(e.openBlock(),e.createElementBlock("span",{key:3,class:"input-suffix",onClick:m},[e.createVNode(r.default,{name:"x",size:16})])):e.createCommentVNode("v-if",!0)],2),t.errorMessage?(e.openBlock(),e.createElementBlock("div",x,e.toDisplayString(t.errorMessage),1)):e.createCommentVNode("v-if",!0)]))}});exports.default=B;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=BaseInput.vue2.cjs.map
