"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */Object.defineProperty(exports,"__esModule",{value:!0});var e=require("vue");require("./BaseInput.vue.cjs");var p=require("./BaseInput.vue2.cjs");const g={class:"image-captcha-wrapper"},f=["src"],v={key:1,class:"captcha-placeholder"},B={key:2,class:"captcha-loading"};var h=e.defineComponent({__name:"ImageCaptcha",props:{modelValue:{type:String,required:!0},imageUrl:{type:String,required:!1},placeholder:{type:String,required:!1,default:"\u8BF7\u8F93\u5165\u9A8C\u8BC1\u7801"},maxlength:{type:Number,required:!1,default:4},errorMessage:{type:String,required:!1},autoLoad:{type:Boolean,required:!1,default:!0}},emits:["update:modelValue","refresh","enter"],setup(i,{emit:d}){const u=i,o=d,n=e.ref(u.modelValue),t=e.ref(!1);let r=null;const m=l=>{n.value=l,o("update:modelValue",l)},c=async()=>{t.value||(t.value=!0,o("refresh"),r!==null&&clearTimeout(r),r=window.setTimeout(()=>{t.value=!1,r=null},500))};return e.onMounted(()=>{u.autoLoad&&!u.imageUrl&&c()}),e.onBeforeUnmount(()=>{r!==null&&(clearTimeout(r),r=null)}),(l,a)=>(e.openBlock(),e.createElementBlock("div",g,[e.createVNode(p.default,{modelValue:n.value,"onUpdate:modelValue":[a[0]||(a[0]=s=>n.value=s),m],placeholder:l.placeholder,maxlength:l.maxlength,"error-message":l.errorMessage,"prefix-icon":"icon-shield",onEnter:a[1]||(a[1]=s=>l.$emit("enter"))},null,8,["modelValue","placeholder","maxlength","error-message"]),e.createElementVNode("div",{class:"captcha-image-container",onClick:c},[l.imageUrl?(e.openBlock(),e.createElementBlock("img",{key:0,src:l.imageUrl,alt:"\u9A8C\u8BC1\u7801",class:e.normalizeClass(["captcha-image",{loading:t.value}]),loading:"lazy",decoding:"async"},null,10,f)):(e.openBlock(),e.createElementBlock("div",v,[...a[2]||(a[2]=[e.createElementVNode("span",null,"\u70B9\u51FB\u83B7\u53D6\u9A8C\u8BC1\u7801",-1)])])),t.value?(e.openBlock(),e.createElementBlock("div",B,[...a[3]||(a[3]=[e.createElementVNode("span",{class:"loading-spinner"},null,-1)])])):e.createCommentVNode("v-if",!0)])]))}});exports.default=h;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=ImageCaptcha.vue2.cjs.map
