"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */Object.defineProperty(exports,"__esModule",{value:!0});var e=require("vue");require("./BaseInput.vue.cjs"),require("./SmsCaptcha.vue.cjs"),require("./RememberCheckbox.vue.cjs");var n=require("../utils/validators.cjs"),f=require("./BaseInput.vue2.cjs"),C=require("./SmsCaptcha.vue2.cjs"),_=require("./RememberCheckbox.vue2.cjs");const F={class:"form-options"},V={class:"option-links"},g=["disabled"],b={key:0,class:"button-loading"},k={key:1};var E=e.defineComponent({__name:"PhoneLoginForm",props:{loading:{type:Boolean,required:!1,default:!1}},emits:["submit","send-sms","switch-to-username","register"],setup(m,{emit:p}){const c=m,i=p,o=e.reactive({phone:"",smsCode:"",remember:!1}),t=e.reactive({phone:"",smsCode:""}),a=e.computed(()=>c.loading),h=e.computed(()=>o.phone&&o.smsCode),d=r=>{t[r]=""},v=()=>{let r=!0;return o.phone?n.validatePhone(o.phone)||(t.phone="\u8BF7\u8F93\u5165\u6B63\u786E\u7684\u624B\u673A\u53F7",r=!1):(t.phone="\u8BF7\u8F93\u5165\u624B\u673A\u53F7",r=!1),o.smsCode?n.validateSmsCode(o.smsCode)||(t.smsCode="\u8BF7\u8F93\u51656\u4F4D\u6570\u5B57\u9A8C\u8BC1\u7801",r=!1):(t.smsCode="\u8BF7\u8F93\u5165\u9A8C\u8BC1\u7801",r=!1),r},l=()=>{a.value||v()&&i("submit",{...o})},B=r=>{if(!n.validatePhone(r)){t.phone="\u8BF7\u8F93\u5165\u6B63\u786E\u7684\u624B\u673A\u53F7";return}i("send-sms",r)};return(r,u)=>(e.openBlock(),e.createElementBlock("form",{class:"phone-login-form",onSubmit:e.withModifiers(l,["prevent"])},[e.createVNode(f.default,{modelValue:o.phone,"onUpdate:modelValue":[u[0]||(u[0]=s=>o.phone=s),u[1]||(u[1]=s=>d("phone"))],placeholder:"\u8BF7\u8F93\u5165\u624B\u673A\u53F7","prefix-icon":"icon-phone",maxlength:11,"error-message":t.phone,clearable:!0,onEnter:l},null,8,["modelValue","error-message"]),e.createVNode(C.default,{modelValue:o.smsCode,"onUpdate:modelValue":[u[2]||(u[2]=s=>o.smsCode=s),u[3]||(u[3]=s=>d("smsCode"))],phone:o.phone,"error-message":t.smsCode,onSend:B,onEnter:l},null,8,["modelValue","phone","error-message"]),e.createElementVNode("div",F,[e.createVNode(_.default,{modelValue:o.remember,"onUpdate:modelValue":u[4]||(u[4]=s=>o.remember=s)},null,8,["modelValue"]),e.createElementVNode("div",V,[e.createElementVNode("a",{href:"#",class:"option-link",onClick:u[5]||(u[5]=e.withModifiers(s=>r.$emit("switch-to-username"),["prevent"]))}," \u7528\u6237\u540D\u767B\u5F55 "),u[7]||(u[7]=e.createElementVNode("span",{class:"divider"},"|",-1)),e.createElementVNode("a",{href:"#",class:"option-link",onClick:u[6]||(u[6]=e.withModifiers(s=>r.$emit("register"),["prevent"]))}," \u7ACB\u5373\u6CE8\u518C ")])]),e.createElementVNode("button",{type:"submit",class:e.normalizeClass(["login-button",{loading:a.value}]),disabled:a.value||!h.value},[a.value?(e.openBlock(),e.createElementBlock("span",b)):(e.openBlock(),e.createElementBlock("span",k,"\u767B\u5F55"))],10,g)],32))}});exports.default=E;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=PhoneLoginForm.vue2.cjs.map
