"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */const i=new WeakMap;function P(t){const n=t.install;t.install=async function(e){await n.call(this,e);const r=e.engine||e;if(await Promise.resolve(),await Promise.resolve(),await Promise.resolve(),!r.router)return;const s=r.router,a=[],d=(o,h,u)=>{if(o.meta?.requiresAuth&&localStorage.getItem("isLoggedIn")!=="true"){u({path:"/login",query:{redirect:o.fullPath}});return}if(o.meta?.roles){const w=localStorage.getItem("userRole")||"guest";if(!o.meta.roles.includes(w)){u("/403");return}}u()},c=s.beforeEach(d);typeof c=="function"&&a.push(c);const m=(o,h)=>{const u=o.meta?.title;u?document.title=`${u} - LDesign Simple App`:document.title="LDesign Simple App"},l=s.afterEach(m);typeof l=="function"&&a.push(l);const p=o=>{console.error("[\u8DEF\u7531\u5B88\u536B] \u5BFC\u822A\u9519\u8BEF:",o),r.notification&&r.notification.error({title:"\u5BFC\u822A\u9519\u8BEF",message:o.message})},g=s.onError(p);typeof g=="function"&&a.push(g),a.length>0&&(i.set(s,a),typeof r.onBeforeUnmount=="function"&&r.onBeforeUnmount(()=>{f(s)}))}}function f(t){const n=i.get(t);n&&(n.forEach(e=>{try{e()}catch(r){console.warn("Error during router guards cleanup:",r)}}),i.delete(t))}function G(){return(t,n,e)=>{const r=localStorage.getItem("isLoggedIn")==="true";t.meta?.requiresAuth&&!r?e({path:"/login",query:{redirect:t.fullPath}}):e()}}function y(){return(t,n,e)=>{if(t.meta?.roles){const r=localStorage.getItem("userRole")||"guest";t.meta.roles.includes(r)?e():e("/403")}else e()}}function A(){return{before:(t,n,e)=>{window.NProgress&&window.NProgress.start(),e()},after:()=>{window.NProgress&&window.NProgress.done()}}}exports.cleanupRouterGuards=f,exports.createAuthGuard=G,exports.createPermissionGuard=y,exports.createProgressGuard=A,exports.setupGuards=P;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=guards.cjs.map
