"use strict";var s=Object.create;var n=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var y=Object.getOwnPropertyNames;var c=Object.getPrototypeOf,d=Object.prototype.hasOwnProperty;var f=(t,a,o,r)=>{if(a&&typeof a=="object"||typeof a=="function")for(let u of y(a))!d.call(t,u)&&u!==o&&n(t,u,{get:()=>a[u],enumerable:!(r=h(a,u))||r.enumerable});return t};var e=(t,a,o)=>(o=t!=null?s(c(t)):{},f(a||!t||!t.__esModule?n(o,"default",{value:t,enumerable:!0}):o,t));/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */Object.defineProperty(exports,"__esModule",{value:!0});const b=()=>import("@/views/Main.vue"),A=()=>import("@/views/Home.vue"),v=()=>import("@/views/Login.vue"),K=()=>import("@/views/Dashboard.vue"),q=()=>import("@/views/About.vue"),R=()=>import("@/views/CryptoDemo.vue"),g=()=>import("@/views/HttpDemo.vue"),D=()=>import("@/views/ApiDemo.vue"),l=[{path:"/",name:"home",component:b,meta:{titleKey:"nav.home",requiresAuth:!1,layout:"default"},children:[{path:"",name:"Home",component:A,meta:{titleKey:"nav.home",requiresAuth:!1,layout:"default"}},{path:"about",name:"About",component:q,meta:{titleKey:"nav.about",requiresAuth:!1,layout:"default"}},{path:"crypto",name:"CryptoDemo",component:R,meta:{titleKey:"nav.crypto",requiresAuth:!1,layout:"default"}},{path:"http",name:"HttpDemo",component:g,meta:{titleKey:"nav.http",requiresAuth:!1,layout:"default"}},{path:"api",name:"ApiDemo",component:D,meta:{titleKey:"nav.api",requiresAuth:!1,layout:"default"}}]},{path:"/login",name:"login",component:v,meta:{titleKey:"nav.login",requiresAuth:!1,layout:"blank"}}],m=[{path:"/dashboard",name:"dashboard",component:K,meta:{titleKey:"nav.dashboard",requiresAuth:!1,layout:"default",roles:["user","admin"]}}],p=[{path:"/:pathMatch(.*)*",name:"not-found",component:()=>import("@/views/errors/NotFound.vue"),meta:{titleKey:"errors.404.title",layout:"blank"}}],i=[...l,...m,...p];exports.authRoutes=m,exports.default=i,exports.errorRoutes=p,exports.publicRoutes=l,exports.routes=i;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=routes.cjs.map
