"use strict";/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */Object.defineProperty(exports,"__esModule",{value:!0});var e=require("vue"),f=require("../i18n/index.cjs"),o=require("../locales/index.cjs"),u=require("lucide-vue-next");const C={class:"language-switcher"},w=["title"],E={class:"flag"},y={class:"name"},B=["onClick"],N={class:"flag"},V={class:"name"};var h=e.defineComponent({__name:"LanguageSwitcher",setup(L){const{locale:i,setLocale:d,t:v}=f.useI18n(),a=e.ref(!1),n=e.computed(()=>i.value),c=e.computed(()=>o.availableLocales.find(l=>l.code===n.value)||o.availableLocales[0]),m=e.computed(()=>c.value.name),p=e.computed(()=>c.value.flag),g=()=>{a.value=!a.value},k=async l=>{await d(l),a.value=!1},r=l=>{l.target.closest(".language-switcher")||(a.value=!1)};return e.onMounted(()=>{document.addEventListener("click",r)}),e.onUnmounted(()=>{document.removeEventListener("click",r)}),(l,s)=>(e.openBlock(),e.createElementBlock("div",C,[e.createElementVNode("button",{onClick:g,class:"language-button",title:e.unref(v)("nav.language")},[e.createElementVNode("span",E,e.toDisplayString(p.value),1),e.createElementVNode("span",y,e.toDisplayString(m.value),1),e.createVNode(e.unref(u.ChevronDown),{class:e.normalizeClass(["arrow",{open:a.value}])},null,8,["class"])],8,w),e.createVNode(e.Transition,{name:"dropdown"},{default:e.withCtx(()=>[a.value?(e.openBlock(),e.createElementBlock("div",{key:0,class:"language-dropdown",onClick:s[0]||(s[0]=e.withModifiers(()=>{},["stop"]))},[(e.openBlock(!0),e.createElementBlock(e.Fragment,null,e.renderList(e.unref(o.availableLocales),t=>(e.openBlock(),e.createElementBlock("button",{key:t.code,onClick:b=>k(t.code),class:e.normalizeClass(["language-option",{active:n.value===t.code}])},[e.createElementVNode("span",N,e.toDisplayString(t.flag),1),e.createElementVNode("span",V,e.toDisplayString(t.name),1),n.value===t.code?(e.openBlock(),e.createBlock(e.unref(u.Check),{key:0,class:"check"})):e.createCommentVNode("v-if",!0)],10,B))),128))])):e.createCommentVNode("v-if",!0)]),_:1})]))}});exports.default=h;/*! End of ldesign-simple-app | Powered by @ldesign/builder */
//# sourceMappingURL=LanguageSwitcher.vue2.cjs.map
