/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */const i=new WeakMap;function P(t){const n=t.install;t.install=async function(e){await n.call(this,e);const o=e.engine||e;if(await Promise.resolve(),await Promise.resolve(),await Promise.resolve(),!o.router)return;const s=o.router,a=[],m=(r,h,u)=>{if(r.meta?.requiresAuth&&localStorage.getItem("isLoggedIn")!=="true"){u({path:"/login",query:{redirect:r.fullPath}});return}if(r.meta?.roles){const w=localStorage.getItem("userRole")||"guest";if(!r.meta.roles.includes(w)){u("/403");return}}u()},c=s.beforeEach(m);typeof c=="function"&&a.push(c);const d=(r,h)=>{const u=r.meta?.title;u?document.title=`${u} - LDesign Simple App`:document.title="LDesign Simple App"},l=s.afterEach(d);typeof l=="function"&&a.push(l);const p=r=>{console.error("[\u8DEF\u7531\u5B88\u536B] \u5BFC\u822A\u9519\u8BEF:",r),o.notification&&o.notification.error({title:"\u5BFC\u822A\u9519\u8BEF",message:r.message})},f=s.onError(p);typeof f=="function"&&a.push(f),a.length>0&&(i.set(s,a),typeof o.onBeforeUnmount=="function"&&o.onBeforeUnmount(()=>{g(s)}))}}function g(t){const n=i.get(t);n&&(n.forEach(e=>{try{e()}catch(o){console.warn("Error during router guards cleanup:",o)}}),i.delete(t))}function y(){return(t,n,e)=>{const o=localStorage.getItem("isLoggedIn")==="true";t.meta?.requiresAuth&&!o?e({path:"/login",query:{redirect:t.fullPath}}):e()}}function B(){return(t,n,e)=>{if(t.meta?.roles){const o=localStorage.getItem("userRole")||"guest";t.meta.roles.includes(o)?e():e("/403")}else e()}}function E(){return{before:(t,n,e)=>{window.NProgress&&window.NProgress.start(),e()},after:()=>{window.NProgress&&window.NProgress.done()}}}/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{g as cleanupRouterGuards,y as createAuthGuard,B as createPermissionGuard,E as createProgressGuard,P as setupGuards};
//# sourceMappingURL=guards.js.map
