/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */class n{constructor(){Object.defineProperty(this,"metrics",{enumerable:!0,configurable:!0,writable:!0,value:{}}),Object.defineProperty(this,"reported",{enumerable:!0,configurable:!0,writable:!0,value:!1}),!(typeof window>"u")&&this.observePerformance()}observePerformance(){this.observePaint(),this.observeLCP(),this.observeCLS(),this.observeFID(),document.readyState==="complete"?this.report():window.addEventListener("load",()=>{setTimeout(()=>this.report(),0)})}observePaint(){try{performance.getEntriesByType("paint").forEach(e=>{e.name==="first-contentful-paint"&&(this.metrics.FCP=e.startTime)})}catch{}}observeLCP(){try{new PerformanceObserver(e=>{const t=e.getEntries(),o=t[t.length-1];this.metrics.LCP=o.startTime}).observe({entryTypes:["largest-contentful-paint"]})}catch{}}observeCLS(){try{let e=0;new PerformanceObserver(t=>{for(const o of t.getEntries())o.hadRecentInput||(e+=o.value,this.metrics.CLS=e)}).observe({entryTypes:["layout-shift"]})}catch{}}observeFID(){try{new PerformanceObserver(e=>{const t=e.getEntries()[0];this.metrics.FID=t.processingStart-t.startTime}).observe({entryTypes:["first-input"]})}catch{}}report(){if(this.reported)return;this.reported=!0;const e=performance.getEntriesByType("navigation")[0];e&&(this.metrics.TTFB=e.responseStart-e.requestStart),import.meta.env.DEV&&console.log("\u{1F4CA} Performance Metrics:",{...this.metrics,"DOM Content Loaded":e?Math.round(e.domContentLoadedEventEnd-e.fetchStart):0,"Load Complete":e?Math.round(e.loadEventEnd-e.fetchStart):0})}getMetrics(){return{...this.metrics}}}const s=new n;function a(r){typeof performance<"u"&&performance.mark&&performance.mark(r)}function i(r,e,t){if(typeof performance<"u"&&performance.measure)try{performance.measure(r,e,t);const o=performance.getEntriesByName(r)[0];import.meta.env.DEV&&console.log(`\u23F1\uFE0F ${r}: ${Math.round(o.duration)}ms`)}catch{}}/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{a as markPerformance,i as measurePerformance,s as performanceMonitor};
//# sourceMappingURL=performance.js.map
