/*!
 * ***********************************
 * ldesign-simple-app v1.0.0       *
 * Built with rollup               *
 * Build time: 2024-10-21 11:21:49 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{appConfig as g}from"../config/app.config.js";const{prefix:i,expire:u}=g.storage;class c{constructor(e){Object.defineProperty(this,"prefix",{enumerable:!0,configurable:!0,writable:!0,value:void 0}),this.prefix=e}getKey(e){return`${this.prefix}${e}`}set(e,t,r){const o={value:t,timestamp:Date.now(),expire:r?Date.now()+r:void 0};try{localStorage.setItem(this.getKey(e),JSON.stringify(o))}catch(a){console.error("Storage set error:",a)}}get(e,t){try{const r=localStorage.getItem(this.getKey(e));if(!r)return t;const o=JSON.parse(r);return o.expire&&o.expire<Date.now()?(this.remove(e),t):o.value}catch(r){return console.error("Storage get error:",r),t}}remove(e){try{localStorage.removeItem(this.getKey(e))}catch(t){console.error("Storage remove error:",t)}}clear(){try{Object.keys(localStorage).forEach(e=>{e.startsWith(this.prefix)&&localStorage.removeItem(e)})}catch(e){console.error("Storage clear error:",e)}}has(e){return localStorage.getItem(this.getKey(e))!==null}keys(){const e=[],t=this.prefix.length;return Object.keys(localStorage).forEach(r=>{r.startsWith(this.prefix)&&e.push(r.substring(t))}),e}}const h=new c(i);class l extends c{set(e,t,r){const o={value:t,timestamp:Date.now(),expire:r?Date.now()+r:void 0};try{s.setItem(this.getKey(e),JSON.stringify(o))}catch(a){console.error("SessionStorage set error:",a)}}get(e,t){try{const r=s.getItem(this.getKey(e));if(!r)return t;const o=JSON.parse(r);return o.expire&&o.expire<Date.now()?(this.remove(e),t):o.value}catch(r){return console.error("SessionStorage get error:",r),t}}remove(e){try{s.removeItem(this.getKey(e))}catch(t){console.error("SessionStorage remove error:",t)}}clear(){try{Object.keys(s).forEach(e=>{e.startsWith(this.prefix)&&s.removeItem(e)})}catch(e){console.error("SessionStorage clear error:",e)}}has(e){return s.getItem(this.getKey(e))!==null}keys(){const e=[],t=this.prefix.length;return Object.keys(s).forEach(r=>{r.startsWith(this.prefix)&&e.push(r.substring(t))}),e}getKey(e){return`${this.prefix}${e}`}}const s=new l(i);/*! End of ldesign-simple-app | Powered by @ldesign/builder */export{s as sessionStorage,h as storage};
//# sourceMappingURL=storage.js.map
